### ISSUE TITLE
Fix biome errors

### ISSUE THREAD

**Issue by frank-bee** [B-S-F/yaku#110]
There is still a couple of biome errors when running
```
 npx @biomejs/biome check --max-diagnostics=none --fix  
```
(mainly in the ui)

**Comment by wulmer** [comment]
You cannot run biome via the command above as it doesn't recognize the `.gitignore` files.

(First, it is not configured to use the `.gitignore` files in the `biome.json` file and second, there is a bug in biome (https://github.com/biomejs/biome/issues/2312) with nested `.gitignore` files).

When I run it with `pre-commit run biome-check -a`, there are a handful of errors which I will fix now.
